---
- name: Create keyring directory for Docker repo
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'

- name: Add Docker GPG Key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: yes
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'

- name: Add Docker repository
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'

- name: Install containerd (Debian/Ubuntu)
  apt:
    name: containerd.io
    state: present
    update_cache: yes
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'

- name: Install DNF Plugin
  dnf:
    name: dnf-plugins-core
    state: present
  when:
    - ansible_facts['distribution'] == 'RedHat' or ansible_facts['distribution'] == 'CentOS'
    - ansible_facts['lsb']['major_release'] | int >= 8

- name: Add Docker CE repo (RedHat/CentOS)
  yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/rhel/$releasever/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/rhel/gpg
  when:
    - ansible_facts['distribution'] == 'RedHat' or ansible_facts['distribution'] == 'CentOS'
    - ansible_facts['lsb']['major_release'] | int >= 8

- name: Install containerd (RedHat/CentOS)
  dnf:
    name: containerd.io
    state: present
  when:
    - ansible_facts['distribution'] == 'RedHat' or ansible_facts['distribution'] == 'CentOS'
    - ansible_facts['lsb']['major_release'] | int >= 8

- name: Create containerd config directory
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: generate default containerd config
  command: containerd config default
  register: containerd_default_config
  changed_when: false

- name: Write containerd config
  copy:
    content: "{{ containerd_default_config.stdout }}"
    owner: root
    group: root
    mode: '0644'

- name: Enable SystemdCgroup in containerd config
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup\s*=\s*false'
    replace: 'SystemdCgroup = true'
  notify: restart containerd

- name: Enable and start containerd service
  systemd:
    name: containerd
    enabled: yes
    state: started
    daemon_reload: yes