---
- name: Set Docker repo architecture
  set_fact:
    docker_arch: >-
      {{ 'amd64' if ansible_architecture == 'x86_64'
         else 'arm64' if ansible_architecture == 'aarch64'
         else ansible_architecture }}

- name: Create keyring directory for Docker repo
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Add Docker GPG Key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: yes
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Add Docker repository
  apt_repository:
    repo: >-
      deb [arch={{ docker_arch }} signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}
      {{ ansible_facts['distribution_release'] }} stable
    state: present
    filename: docker
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Install Docker (Ubuntu)
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Create Docker daemon directory
  file:
    path: /etc/docker/
    state: directory
    mode: '0755'

- name: Create Docker daemon (Ubuntu)
  template:
    src: docker-daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: "0644"
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Create Docker systemd directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: yes
    state: restarted
    daemon_reload: yes