---
- name: Update package cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Install HAProxy & KeepAlived
  ansible.builtin.apt:
    name: 
    - haproxy
    - keepalived
    - iproute2
    - iputils-ping
    state: present
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Install HAProxy & KeepAlived (RHEL/CentOS 8)
  ansible.builtin.dnf:
    name:
      - haproxy
      - keepalived
      - iproute
      - iputils
    state: present
  when:
    - ansible_facts['distribution'] == 'RedHat' or ansible_facts['distribution'] == 'CentOS'
    - ansible_facts['lsb']['major_release'] | int >= 8

- name: Configure sysctl parameters for HAProxy and KeepAlived
  copy:
    dest: /etc/sysctl.d/haproxy.conf
    content: |
      net.ipv4.ip_nonlocal_bind = 1
    mode: '0644'
  notify: Apply sysctl

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify: Restart haproxy

- name: Configure KeepAlived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'
  notify: Restart keepalived

- name: Enable and start HAProxy
  systemd:
    name: haproxy
    state: started
    enabled: yes

- name: Enable and start Keepalived
  systemd:
    name: keepalived
    state: started
    enabled: yes