---
- name: Check if Kubernetes is already initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubeadm_init

- name: Create kubeadm configuration
  template:
    src: kubeadm-config.yaml.j2
    dest: /etc/kubernetes/kubernetes-config.yaml
    mode: "0644"

- name: Initialize Kubernetes cluster
  command: kubeadm init --config /etc/kubernetes/kubernetes-config.yaml
  when: not kubeadm_init.stat.exists
  register: kubeadm_init_output

# - name: Copy admin.conf to root's kube config
#   copy:
#     src: /etc/kubernetes/admin.conf
#     dest: /root/.kube/config
#     remote_src: yes
#     owner: root
#     group: root
#     mode: '0644'

- name: Create kube config
  shell: |
    mkdir -p $HOME/.kube
    sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config

- name: Generate join command
  shell: kubeadm token create --print-join-command
  register: join_command_output

- name: Save join command to file
  copy:
    content: "{{ join_command_output.stdout }}"
    dest: /tmp/kubernetes_join_command.sh
    mode: '0755'

- name: Fetch join command to local machine
  fetch:
    src: /tmp/kubernetes_join_command.sh
    dest: /tmp/kubernetes_join_command.sh
    flat: yes
