---
- name: Add Kubernetes yum repository (RedHat/CentOS)
  copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    content: |
      name=Kubernetes
      baseurl=https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version.split('.')[0] }}.{{ kubernetes_version.split('.')[1] }}/rpm/
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version.split('.')[0] }}.{{ kubernetes_version.split('.')[1] }}/rpm/repodata/repomd.xml.key
      exclude=kubelet kubeadm kubectl
  when: 
    - ansible_facts['distribution'] == 'RedHat' or ansible_facts['distribution'] == 'CentOS'
    - ansible_facts['lsb']['major_release'] | int >= 8

- name: Disable SELinux runtime (RedHat/CentOS)
  command: setenforce 0
  when:
    - ansible_facts['distribution'] == 'RedHat' or ansible_facts['distribution'] == 'CentOS'
    - ansible_facts['lsb']['major_release'] | int >= 8
  ignore_errors: true

- name: Disable SELinux permanently (CentOS)
  replace:
    path: /etc/sysconfig/selinux
    regexp: 'SELINUX=enforcing'
    replace: 'SELINUX=disabled'
    follow: yes
  when:
    - ansible_facts['distribution'] == 'CentOS'
    - ansible_facts['lsb']['major_release'] | int >= 8

- name: Set SELinux to permissive permanently (RHEL)
  replace:
    path: /etc/selinux/config
    regexp: '^SELINUX=enforcing$'
    replace: 'SELINUX=permissive'
  when:
    - ansible_facts['distribution'] == 'RedHat'
    - ansible_facts['lsb']['major_release'] | int >= 8

- name: Upgrade all packages (RedHat/CentOS)
  dnf:
    name: "*"
    state: latest
    update_cache: yes
  when:
    - ansible_facts['distribution'] == 'RedHat' or ansible_facts['distribution'] == 'CentOS'
    - ansible_facts['lsb']['major_release'] | int >= 8

- name: Install Kubernetes packages (RedHat/CentOS)
  dnf:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    disable_excludes: kubernetes
  when:
    - ansible_facts['distribution'] == 'RedHat' or ansible_facts['distribution'] == 'CentOS'
    - ansible_facts['lsb']['major_release'] | int >= 8

- name: Enable kubelet service
  systemd:
    name: kubelet
    enabled: yes
    daemon_reload: yes
    state: started